#!/bin/bash

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"

OUTPUT_FILE="$ROOT_DIR/infra/nginx/default.conf.lb.template"
SINGLE_MODE=0
SERVICE=""
DOMAIN=""
FORCE_APPEND=0

usage() {
  cat <<USAGE
Usage: $0 --single --service=NAME --domain=DOMAIN [options]

Options:
  --single
  --service=NAME        app|hmr|s3|s3-console|pma|reverb
  --domain=DOMAIN       Hostname (can be URL, will be normalized)
  --output=PATH         Output LB template file (default: infra/nginx/default.conf.lb.template)
  --force-append        Append even if same domain already exists
  --help
USAGE
}

extract_host() {
  local host="$1"
  host="${host#http://}"
  host="${host#https://}"
  host="${host%%/*}"
  host="${host%%:*}"
  printf '%s\n' "$host"
}

load_env() {
  local f="$1"
  if [ -f "$f" ]; then
    set -a
    source "$f"
    set +a
  fi
}

init_lb_if_missing() {
  local file="$1"
  [ -f "$file" ] && return

  mkdir -p "$(dirname "$file")"
  cat > "$file" <<'EOF'
# Generated by setup-nginx-template.sh (single append mode)

log_format json_analytics escape=json '{'
    '"time_local":"$time_local",'
    '"remote_addr":"$remote_addr",'
    '"host":"$host",'
    '"request":"$request",'
    '"status":"$status",'
    '"body_bytes_sent":"$body_bytes_sent",'
    '"request_time":"$request_time",'
    '"upstream_addr":"$upstream_addr",'
    '"upstream_status":"$upstream_status",'
    '"upstream_response_time":"$upstream_response_time",'
    '"http_referrer":"$http_referer",'
    '"http_user_agent":"$http_user_agent"'
'}';

resolver 127.0.0.11 valid=10s;
access_log /dev/stdout json_analytics;
error_log /dev/stderr warn;

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}

server {
    listen 80;
    server_name load_balancer;

    location /stub_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        allow 172.16.0.0/12;
        allow 0.0.0.0/8;
        deny all;
    }
}
EOF
}

append_lb_block() {
  local file="$1"
  local service="$2"
  local domain="$3"

  local app_service="${APP_SERVICE:-app}"
  local app_port="${APP_PORT:-8000}"
  local minio_service="${MINIO_SERVICE:-minio}"
  local minio_port="${MINIO_PORT:-9000}"
  local minio_console_port="${MINIO_CONSOLE_PORT:-9001}"
  local reverb_server_port="${REVERB_SERVER_PORT:-18080}"

  if [ "$FORCE_APPEND" -ne 1 ] && grep -qE "^[[:space:]]*server_name[[:space:]]+${domain}[;[:space:]]" "$file"; then
    echo -e "${YELLOW}[SKIP]${NC} Domain '$domain' already exists in $file"
    return
  fi

  {
    echo ""
    echo "# --- GENERATED LB ENTRY: ${service}:${domain} ---"
    case "$service" in
      app)
        cat <<EOF
server {
    listen 80;
    server_name ${domain};

    location / {
        proxy_pass http://${app_service}:${app_port};
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$proxy_x_forwarded_proto;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
    }
}
EOF
        ;;
      hmr)
        cat <<EOF
server {
    listen 80;
    server_name ${domain};

    client_max_body_size 500M;

    location / {
        proxy_pass http://app-hmr:5173;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$proxy_x_forwarded_proto;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
    }
}
EOF
        ;;
      s3)
        cat <<EOF
server {
    listen 80;
    server_name ${domain};

    client_max_body_size 100M;

    location / {
        proxy_pass http://${minio_service}:${minio_port};
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$proxy_x_forwarded_proto;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
    }
}
EOF
        ;;
      s3-console)
        cat <<EOF
server {
    listen 80;
    server_name ${domain};

    location / {
        proxy_pass http://${minio_service}:${minio_console_port};
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$proxy_x_forwarded_proto;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
    }
}
EOF
        ;;
      pma)
        cat <<EOF
server {
    listen 80;
    server_name ${domain};

    location / {
        proxy_pass http://phpmyadmin:80;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$proxy_x_forwarded_proto;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
    }
}
EOF
        ;;
      reverb)
        cat <<EOF
server {
    listen 80;
    server_name ${domain};

    location / {
        proxy_pass http://app-socket:${reverb_server_port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$proxy_x_forwarded_proto;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }
}
EOF
        ;;
      *)
        echo -e "${RED}[ERROR]${NC} Unsupported service: $service"
        exit 1
        ;;
    esac
  } >> "$file"

  echo -e "${GREEN}[OK]${NC} Appended LB entry ${service}:${domain} into $file"
}

for arg in "$@"; do
  case "$arg" in
    --single) SINGLE_MODE=1 ;;
    --service=*) SERVICE="${arg#*=}" ;;
    --domain=*) DOMAIN="${arg#*=}" ;;
    --output=*) OUTPUT_FILE="${arg#*=}" ;;
    --force-append) FORCE_APPEND=1 ;;
    --help) usage; exit 0 ;;
    *) echo -e "${RED}[ERROR]${NC} Unknown argument: $arg"; usage; exit 1 ;;
  esac
done

load_env "$ROOT_DIR/.env"
load_env "$ROOT_DIR/.env.backend"
load_env "$ROOT_DIR/.env.devops"

if [ "$SINGLE_MODE" -ne 1 ]; then
  echo -e "${RED}[ERROR]${NC} Only single mode is supported. Use --single"
  usage
  exit 1
fi

[ -z "$SERVICE" ] && { echo -e "${RED}[ERROR]${NC} --service is required"; exit 1; }

if [ -z "$DOMAIN" ]; then
  case "$SERVICE" in
    app) DOMAIN="${APP_DOMAIN:-}" ;;
    hmr) DOMAIN="${HMR_URL:-}" ;;
    s3) DOMAIN="${S3_DOMAIN:-${S3_URL:-}}" ;;
    s3-console) DOMAIN="${S3_CONSOLE_DOMAIN:-${S3_CONSOLE_URL:-}}" ;;
    pma) DOMAIN="${PMA_DOMAIN:-${PMA_ABSOLUTE_URI:-${PHPMYADMIN_URL:-}}}" ;;
    reverb) DOMAIN="${REVERB_DOMAIN:-${REVERB_URL:-}}" ;;
  esac
fi

DOMAIN="$(extract_host "$DOMAIN")"
[ -z "$DOMAIN" ] && { echo -e "${RED}[ERROR]${NC} Invalid/empty domain"; exit 1; }

init_lb_if_missing "$OUTPUT_FILE"
append_lb_block "$OUTPUT_FILE" "$SERVICE" "$DOMAIN"
