#!/bin/bash

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"

OUTPUT_FILE="$ROOT_DIR/infra/nginx/default.conf"
TEMPLATE_FILE="$ROOT_DIR/infra/nginx/default.conf.lb.template"

# Legacy flags (bulk generation)
ENABLE_MINIO=0
ENABLE_PMA=0
ENABLE_REVERB=0
ENABLE_HMR=-1

# New single-entry flags
SINGLE_MODE=0
SERVICE=""
DOMAIN=""
APP_DOMAIN_ARG=""
FORCE_APPEND=0

usage() {
    cat <<USAGE
Usage: $0 [options]

Single-entry mode (recommended for micro deployment):
  --single                     Enable 1-1 generation mode
  --service=NAME               app|hmr|s3|s3-console|pma|reverb
  --domain=DOMAIN              Domain for selected service
  --app-domain=DOMAIN          Optional app domain (used by app service fallback)
  --output=PATH                Output file (default: infra/nginx/default.conf)
  --force-append               Append even if same domain already exists

Bulk mode (legacy):
  --enable-minio
  --enable-pma
  --enable-reverb
  --enable-hmr
  --disable-hmr
  --all

Common:
  --help
USAGE
}

load_env() {
    local f="$1"
    if [ -f "$f" ]; then
        set -a
        source "$f"
        set +a
    fi
}

extract_host() {
    local host="$1"
    host="${host#http://}"
    host="${host#https://}"
    host="${host%%/*}"
    host="${host%%:*}"
    printf '%s\n' "$host"
}

init_lb_file_if_missing() {
    local file="$1"
    if [ -f "$file" ]; then
        return
    fi

    mkdir -p "$(dirname "$file")"
    cat > "$file" <<'EOF'
# Generated by scripts/setup/setup-nginx.sh (single mode)
# This file supports incremental append per service/domain.

log_format json_analytics escape=json '{'
    '"time_local":"$time_local",'
    '"remote_addr":"$remote_addr",'
    '"host":"$host",'
    '"request":"$request",'
    '"status":"$status",'
    '"body_bytes_sent":"$body_bytes_sent",'
    '"request_time":"$request_time",'
    '"upstream_addr":"$upstream_addr",'
    '"upstream_status":"$upstream_status",'
    '"upstream_response_time":"$upstream_response_time",'
    '"http_referrer":"$http_referer",'
    '"http_user_agent":"$http_user_agent"'
'}';

resolver 127.0.0.11 valid=10s;
access_log /dev/stdout json_analytics;
error_log /dev/stderr warn;

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}

server {
    listen 80;
    server_name load_balancer;
    location /stub_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        allow 172.16.0.0/12;
        allow 0.0.0.0/8;
        deny all;
    }
}
EOF
}

append_service_block() {
    local file="$1"
    local service="$2"
    local domain="$3"

    local app_service="${APP_SERVICE:-app}"
    local app_port="${APP_PORT:-8000}"
    local minio_service="${MINIO_SERVICE:-minio}"
    local minio_port="${MINIO_PORT:-9000}"
    local minio_console_port="${MINIO_CONSOLE_PORT:-9001}"
    local reverb_server_port="${REVERB_SERVER_PORT:-18080}"

    if [ "$FORCE_APPEND" -ne 1 ] && grep -qE "^[[:space:]]*server_name[[:space:]]+${domain}[;[:space:]]" "$file"; then
        echo -e "${YELLOW}[SKIP]${NC} Domain '$domain' already exists in $file (use --force-append)."
        return
    fi

    {
        echo ""
        echo "# --- GENERATED SERVICE: ${service}:${domain} ---"
        case "$service" in
            app)
                cat <<EOF
server {
    listen 80;
    server_name ${domain};

    location / {
        proxy_pass http://${app_service}:${app_port};
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$proxy_x_forwarded_proto;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
    }
}
EOF
                ;;
            hmr)
                cat <<EOF
server {
    listen 80;
    server_name ${domain};

    client_max_body_size 500M;

    location / {
        proxy_pass http://app-hmr:5173;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$proxy_x_forwarded_proto;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
    }
}
EOF
                ;;
            s3)
                cat <<EOF
server {
    listen 80;
    server_name ${domain};

    client_max_body_size 100M;

    location / {
        proxy_pass http://${minio_service}:${minio_port};
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$proxy_x_forwarded_proto;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
    }
}
EOF
                ;;
            s3-console)
                cat <<EOF
server {
    listen 80;
    server_name ${domain};

    location / {
        proxy_pass http://${minio_service}:${minio_console_port};
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$proxy_x_forwarded_proto;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
    }
}
EOF
                ;;
            pma)
                cat <<EOF
server {
    listen 80;
    server_name ${domain};

    location / {
        proxy_pass http://phpmyadmin:80;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$proxy_x_forwarded_proto;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
    }
}
EOF
                ;;
            reverb)
                cat <<EOF
server {
    listen 80;
    server_name ${domain};

    location / {
        proxy_pass http://app-socket:${reverb_server_port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;
        proxy_set_header Host \$http_host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$proxy_x_forwarded_proto;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }
}
EOF
                ;;
            *)
                echo -e "${RED}[ERROR]${NC} Unsupported service: $service"
                exit 1
                ;;
        esac
    } >> "$file"

    echo -e "${GREEN}[OK]${NC} Appended service '$service' for domain '$domain' into $file"
}

# Parse args
for arg in "$@"; do
    case "$arg" in
        --single) SINGLE_MODE=1 ;;
        --service=*) SERVICE="${arg#*=}" ;;
        --domain=*) DOMAIN="${arg#*=}" ;;
        --app-domain=*) APP_DOMAIN_ARG="${arg#*=}" ;;
        --output=*) OUTPUT_FILE="${arg#*=}" ;;
        --force-append) FORCE_APPEND=1 ;;
        --enable-minio) ENABLE_MINIO=1 ;;
        --enable-pma) ENABLE_PMA=1 ;;
        --enable-reverb) ENABLE_REVERB=1 ;;
        --enable-hmr) ENABLE_HMR=1 ;;
        --disable-hmr) ENABLE_HMR=0 ;;
        --all)
            ENABLE_MINIO=1
            ENABLE_PMA=1
            ENABLE_REVERB=1
            ENABLE_HMR=1
            ;;
        --help)
            usage
            exit 0
            ;;
        *)
            echo -e "${RED}[ERROR]${NC} Unknown argument: $arg"
            usage
            exit 1
            ;;
    esac
done

load_env "$ROOT_DIR/.env"
load_env "$ROOT_DIR/.env.backend"
load_env "$ROOT_DIR/.env.devops"

if [ "$SINGLE_MODE" -eq 1 ]; then
    [ -z "$SERVICE" ] && { echo -e "${RED}[ERROR]${NC} --service wajib diisi di mode --single"; exit 1; }

    if [ -z "$DOMAIN" ]; then
        case "$SERVICE" in
            app) DOMAIN="${APP_DOMAIN_ARG:-${APP_DOMAIN:-}}" ;;
            hmr) DOMAIN="${HMR_URL:-}" ;;
            s3) DOMAIN="${S3_DOMAIN:-${S3_URL:-}}" ;;
            s3-console) DOMAIN="${S3_CONSOLE_DOMAIN:-${S3_CONSOLE_URL:-}}" ;;
            pma) DOMAIN="${PMA_DOMAIN:-${PMA_ABSOLUTE_URI:-${PHPMYADMIN_URL:-}}}" ;;
            reverb) DOMAIN="${REVERB_DOMAIN:-${REVERB_URL:-}}" ;;
        esac
    fi

    DOMAIN="$(extract_host "$DOMAIN")"
    [ -z "$DOMAIN" ] && { echo -e "${RED}[ERROR]${NC} Domain tidak valid/kosong."; exit 1; }

    init_lb_file_if_missing "$OUTPUT_FILE"
    append_service_block "$OUTPUT_FILE" "$SERVICE" "$DOMAIN"
    exit 0
fi

# Legacy bulk generation path
if [ "$ENABLE_HMR" -eq -1 ]; then
    if [ -n "${HMR_URL:-}" ]; then
        ENABLE_HMR=1
    else
        ENABLE_HMR=0
    fi
fi

echo "🛠️  Generating Nginx Configuration (bulk mode)..."

if [ ! -f "$TEMPLATE_FILE" ]; then
    echo -e "${RED}[ERROR]${NC} Template not found: $TEMPLATE_FILE"
    exit 1
fi

TMP_FILE="$(mktemp)"
cp "$TEMPLATE_FILE" "$TMP_FILE"

remove_section_between() {
    local file="$1"
    local start_marker="$2"
    local end_marker="$3"
    local tmp
    tmp="$(mktemp)"
    awk -v start="$start_marker" -v end="$end_marker" '
        $0 == start {skip=1; next}
        skip && $0 == end {skip=0}
        !skip {print}
    ' "$file" > "$tmp"
    mv "$tmp" "$file"
}

remove_section_to_eof() {
    local file="$1"
    local start_marker="$2"
    local tmp
    tmp="$(mktemp)"
    awk -v start="$start_marker" '
        $0 == start {skip=1}
        !skip {print}
    ' "$file" > "$tmp"
    mv "$tmp" "$file"
}

if [ "$ENABLE_HMR" -ne 1 ]; then
    remove_section_between "$TMP_FILE" '# --- App Service (HMR) ---' '# --- MINIO S3 Storage ---'
    echo -e "${YELLOW}[SKIP]${NC} HMR Service not included."
fi
if [ "$ENABLE_MINIO" -ne 1 ]; then
    remove_section_between "$TMP_FILE" '# --- MINIO S3 Storage ---' '# --- MINIO Console ---'
    remove_section_between "$TMP_FILE" '# --- MINIO Console ---' '# --- PHPMYADMIN ---'
    echo -e "${YELLOW}[SKIP]${NC} MinIO Services not included."
fi
if [ "$ENABLE_PMA" -ne 1 ]; then
    remove_section_between "$TMP_FILE" '# --- PHPMYADMIN ---' '# --- REVERB ---'
    echo -e "${YELLOW}[SKIP]${NC} PhpMyAdmin Service not included."
fi
if [ "$ENABLE_REVERB" -ne 1 ]; then
    remove_section_to_eof "$TMP_FILE" '# --- REVERB ---'
    echo -e "${YELLOW}[SKIP]${NC} Reverb Service not included."
fi

VARS='$APP_DOMAIN $APP_SERVICE $APP_PORT $HMR_URL $S3_DOMAIN $S3_URL $S3_CONSOLE_DOMAIN $S3_CONSOLE_URL $MINIO_SERVICE $MINIO_PORT $MINIO_CONSOLE_PORT $PMA_DOMAIN $PHPMYADMIN_URL $REVERB_DOMAIN $REVERB_URL $REVERB_SERVER_PORT'
envsubst "$VARS" < "$TMP_FILE" > "$OUTPUT_FILE"
rm -f "$TMP_FILE"

echo -e "${GREEN}[OK]${NC} Generated Nginx config at $OUTPUT_FILE"
