apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:${PROMETHEUS_PORT}  # Membaca env var
    access: proxy
    isDefault: true

  - name: Loki
    type: loki
    url: http://loki:${LOKI_PORT}
    access: proxy
    basicAuth: true
    basicAuthUser: ${LOKI_USER}      # Membaca env var
    secureJsonData:
      basicAuthPassword: ${LOKI_PASSWORD} # Membaca env var (Sangat disarankan!)